# Generated by Django 4.1.1 on 2022-10-03 22:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registros_actividad',
            fields=[
                ('codactividad', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('horaentrada', models.TimeField()),
                ('horasalida', models.TimeField()),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Registros_cliente',
            fields=[
                ('DNI', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=100)),
                ('fechadealta', models.DateField(default=datetime.date.today)),
                ('observacion', models.CharField(max_length=200)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Registros_instructor',
            fields=[
                ('DNIinstructor', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=10)),
                ('matricula', models.CharField(max_length=20)),
                ('estado', models.BooleanField(default=True)),
                ('fechadealta', models.DateField(default=datetime.date.today)),
                ('email', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Registros_modalidad',
            fields=[
                ('codmodalidad', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resgistros_dia',
            fields=[
                ('coddia', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Registros_registro',
            fields=[
                ('codregistro', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('DNI', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.registros_cliente')),
                ('codactividad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.registros_actividad')),
            ],
        ),
        migrations.CreateModel(
            name='Registros_cliente_actividad',
            fields=[
                ('codclienteactividad', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('DNI', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.registros_cliente')),
                ('codactividad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.registros_actividad')),
            ],
        ),
        migrations.AddField(
            model_name='registros_actividad',
            name='DNIinstructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.registros_instructor'),
        ),
        migrations.AddField(
            model_name='registros_actividad',
            name='coddia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.resgistros_dia'),
        ),
        migrations.AddField(
            model_name='registros_actividad',
            name='codmodalidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.registros_modalidad'),
        ),
    ]
